import React from 'react';
import Footer from '../../containers/footer/Footer'
import './PrivacyPolicy.css';

const PrivacyPolicy = () => {
    return (
        <div>
            <div className='container'>
                <div className='d-flex justify-content-center mt-3' >
                    <h3>Our Privacy Policy</h3>
                </div>
                <div>
                    <p>
                        This Privacy Policy describes our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>
                </div>

                <div>
                    <h4>Interpretation and Definitions</h4>
                </div>
                <div>
                    <h5>Interpretation</h5>
                    <p>
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </p>
                </div>
                <div>
                    <h5>Definitions</h5>
                    <p className='px-3'>
                        For the purposes of this Privacy Policy:<br />
                        <span className='boldText'>Account</span> means a unique account created for you to access our Service or parts of our Service. <br />
                        <span className='boldText'>Trust</span> (referred to as either "the Trust", "We", "Us" or "Our" in this Agreement) refers to Child Care Organization, # 7-813 (3), Samata Nagar, Kurnool Road, Ongole – 2, Prakasham (Dist), Andhra Pradesh - 523002.<br />
                        <span className='boldText'>Cookies</span> are small files that are placed on your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.<br />
                        <span className='boldText'>Device</span> Country refers to India.<br />
                        <span className='boldText'>Personal Data</span> is any information that relates to an identified or identifiable individual.<br />
                        <span className='boldText'>Service</span> refers to the Website.<br />
                        <span className='boldText'>Service Provider</span> means any natural or legal person who processes the data on behalf of the Trust. It refers to third-party companies or individuals employed by the Trust to facilitate the Service, to provide the Service on behalf of the Trust, to perform services related to the Service or to assist the Trust in analyzing how the Service is used.<br />
                        <span className='boldText'>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br />
                        <span className='boldText'>Website</span> refers to <span className='text-uppercase'>ccare93.in</span>, accessible from https://www.ccare93.in/<br />
                        <span className='boldText'>You</span> means the individual accessing or using the Service, or the Trust, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.<br />
                    </p>
                </div>

                <div>
                    <h4>
                        Collecting and Using Your Personal Data
                    </h4>
                    <h5>
                        Types of Data Collected
                    </h5>
                    <h6>Personal Data</h6>
                    <p>
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                    </p>
                    <p>
                        Email address <br />
                        First name and last name <br />
                        Phone number <br />
                        Address, State, Province, ZIP/Postal code, City <br />
                    </p>
                </div>

                <div>
                    <h4>
                        Use of Your Personal Data
                    </h4>
                    <p className='px-3'>
                        The Trust may use Personal Data for the following purposes: <br />
                        <span className='boldText'>To provide and maintain our Service</span> including to monitor the usage of our Service. <br />
                        <span className='boldText'>To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user. <br />
                        <span className='boldText'>For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service. <br />
                        <span className='boldText'>To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. <br />
                        <span className='boldText'>To provide You:</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information. <br />
                        <span className='boldText'>To manage Your requests:</span> To attend and manage Your requests to Us. <br />
                        <span className='boldText'>For transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred. <br />
                        <span className='boldText'>For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience. <br />
                        We may share Your personal information in the following situations: <br />
                        <span className='boldText'>With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. <br />
                        <span className='boldText'>With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent. <br />
                    </p>
                </div>

                <div>
                    <h4>
                        Retention of Your Personal Data
                    </h4>
                    <p>
                        The Trust will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br />
                        The Trust will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                    </p>
                </div>

                <div>
                    <h4>
                        Transfer of Your Personal Data
                    </h4>
                    <p>
                        Your information, including Personal Data, is processed at theTrust operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br />
                        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. <br />
                        The Trust will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                    </p>
                </div>

                <div>
                    <h4>
                        Law enforcement
                    </h4>
                    <p>
                        Under certain circumstances, the Trust may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                    </p>
                </div>

                <div>
                    <h4>
                        Other legal requirements
                    </h4>
                    <p>
                        The Trust may disclose Your Personal Data in the good faith belief that such action is necessary to:
                        Comply with a legal obligation
                        Protect and defend the rights or property of the Trust
                        Prevent or investigate possible wrongdoing in connection with the Service
                        Protect the personal safety of Users of the Service or the public
                        Protect against legal liability .
                    </p>
                </div>

                <div>
                    <h4>
                        Security of Your Personal Data
                    </h4>
                    <p>
                        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                    </p>
                </div>

                <div>
                    <h4>
                        Detailed Information on the Processing of Your Personal Data
                    </h4>
                    <p>
                        The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.
                    </p>
                </div>

                <div>
                    <h4>
                        Usage, Performance and Miscellaneous
                    </h4>
                    <p>
                        We may use third-party Service Providers to provide better improvement of our Service.
                        Google Places Google Places is a service that returns information about places using HTTP requests. It is operated by Google
                        Google Places service may collect information from You and from Your Device for security purposes.
                        Children's Privacy
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                    </p>
                </div>

                <div>
                    <h4>
                        Links to Other Websites
                    </h4>
                    <p>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </p>
                </div>

                <div>
                    <h4>
                        Changes to this Privacy Policy
                    </h4>
                    <p>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </p>
                </div>

                <div>
                    <h4>
                        Donation refund policy:
                    </h4>
                    <p>
                        Child Care Organization doesn't encourage Refund or Cancellation of Funds.
                        For more queries, please contact Child Care Organization office or send us a mail to ccare93@gmail.com
                    </p>
                </div>

                <div>
                    <h4>
                        Contact Us
                    </h4>
                    <p>
                        If you have any questions about this Privacy Policy, You can contact us:<br />
                        By email: ccare93@gmail.com<br />
                        By visiting this page on our website:https://www.ccare93.in/contact-us<br />
                        By phone number: +91-8500497940<br />
                    </p>
                </div>

            </div>
            <Footer />
        </div>
    )
}

export default PrivacyPolicy